task default: :test

desc "Run all test suites"
task :test do
  Dir["gems/*/test/*_test.rb"].each do |f|
    sh "ruby #{f}"
  end
end

desc "Generate docs/events.md from declared event contracts (CI diffs this)"
task :"events:catalog" do
  require_relative "gems/terret-core/lib/terret"
  rows = Hames.catalog.map { |n, m, d, doc| "| `#{n}` | #{m} | #{d ? 'yes' : ''} | #{doc} |" }
  File.write("docs/events.md", <<~MD)
    # Event Catalog

    Generated by `rake events:catalog`. The dispatch mode is part of each
    event's public contract; the bus enforces it at runtime.

    | Event | Mode | Durable | Description |
    |---|---|---|---|
    #{rows.join("\n")}
  MD
  puts "wrote docs/events.md (#{rows.length} events)"
end
