task default: :test

desc "Run all test suites"
task :test do
  # gems/*/test holds each gem's suite; release/test holds the repo-level
  # release tooling's suite (the build/push ordering), which spans every gem
  # and so belongs to no single one.
  (Dir["gems/*/test/*_test.rb"] + Dir["release/test/*_test.rb"]).each do |f|
    sh "ruby #{f}"
  end
end

desc "Generate docs/events.md from declared event contracts (CI diffs this)"
task :"events:catalog" do
  require_relative "gems/terret-core/lib/terret"
  rows = Hames.catalog.map { |n, m, d, doc| "| `#{n}` | #{m} | #{d ? 'yes' : ''} | #{doc} |" }
  File.write("docs/events.md", <<~MD)
    # Event Catalog

    Generated by `rake events:catalog`. The dispatch mode is part of each
    event's public contract; the bus enforces it at runtime.

    | Event | Mode | Durable | Description |
    |---|---|---|---|
    #{rows.join("\n")}
  MD
  puts "wrote docs/events.md (#{rows.length} events)"
end

# Rendering for config:catalog, kept off Object so the Rakefile does not grow
# global helpers. Mirrors the events:catalog shape: walk the declarations the
# code registered, sort deterministically, render markdown, and let CI diff it.
module ConfigCatalog
  module_function

  def sections
    entries.map { |gem, klass, schema| section(gem, klass, schema) }
  end

  def entries
    Hames::Schema.declared.map do |klass, schema|
      source = Object.const_source_location(klass.name)&.first.to_s
      gem = source[%r{/gems/([^/]+)/}, 1] || "?"
      [gem, klass, schema]
    end.sort_by { |gem, klass, _| [gem, klass.name] }
  end

  def section(gem, klass, schema)
    key = (klass.respond_to?(:service_key) && klass.service_key) ? " (`#{klass.service_key}`)" : ""
    header = "## #{gem} — `#{klass.name}`#{key}"
    return "#{header}\n\nNo configurable keys.\n" if schema.keys.empty?

    rows = schema.keys.each_value.map do |spec|
      "| `#{spec.name}` | #{type(spec.type)} | #{spec.required ? 'yes' : ''} | " \
        "#{default(spec.default)} | #{doc(spec.doc)} |"
    end
    "#{header}\n\n| Key | Type | Required | Default | Description |\n|---|---|---|---|---|\n#{rows.join("\n")}\n"
  end

  def type(type)
    return "—" if type.nil?

    types = Array(type)
    return "boolean" if types.sort_by(&:name) == [FalseClass, TrueClass]

    types.join(" or ")
  end

  def default(value) = value.nil? ? "—" : "`#{value.inspect}`"
  def doc(text) = text.to_s.gsub("|", "\\|")
end

desc "Run the bench lane (plan §11): dispatch overhead + chunk throughput. " \
     "BENCH_FLOORS=1 asserts each metric against bench/floors.yml and exits 1 below floor"
task :bench do
  require "yaml"
  require_relative "bench/dispatch_overhead"
  require_relative "bench/chunk_throughput"

  results = {}
  results.merge!(Bench::DispatchOverhead.run)
  results.merge!(Bench::ChunkThroughput.run)

  floors = YAML.safe_load_file("bench/floors.yml")

  puts "\nBench summary"
  puts format("%-38s %14s %14s", "metric", "this run", "floor")
  results.each do |metric, value|
    puts format("%-38s %14d %14d", metric, value, floors.fetch(metric))
  end

  next unless ENV["BENCH_FLOORS"]

  failing = results.select { |metric, value| value < floors.fetch(metric) }
  if failing.empty?
    puts "\nBENCH_FLOORS: all #{results.length} metrics at or above floor"
  else
    warn "\nBENCH_FLOORS: below floor: " \
         "#{failing.map { |m, v| "#{m}=#{v} < #{floors.fetch(m)}" }.join(', ')}"
    exit 1
  end
end

desc "Generate docs/config-catalog.md from every service's Hames::Schema (CI diffs this)"
task :"config:catalog" do
  require_relative "gems/terret/lib/terret/boot"
  require_relative "gems/terret/lib/terret/schema_gems"
  # One shared list (Terret::SCHEMA_GEMS), so every schema a shipped bundle can
  # mount is registered before the catalog is written — and a new configurable
  # gem is added in one place the schema tests read too.
  Terret::SCHEMA_GEMS.each { |f| require f }

  sections = ConfigCatalog.sections
  File.write("docs/config-catalog.md", <<~MD)
    # Config Catalog

    Generated by `rake config:catalog`. Every service that declares a
    Hames::Schema is listed with the config keys it reads — type, whether it is
    required, its default, and what it does. CI diffs this, so a config key that
    changes shape shows up in review rather than in a support thread.

    Injectable seams (a transport, a resolver, a client factory) are wiring
    passed in code, never YAML, so they are absent here by design. A service
    with no schema is not listed; doctor reports it as `unschema'd`.

    #{sections.join("\n")}
  MD
  puts "wrote docs/config-catalog.md (#{ConfigCatalog.entries.length} services)"
end

namespace :release do
  desc "Build every gem into pkg/ with --strict (proof the gemspecs are valid). " \
       "Reversible — pkg/ is gitignored — and the local half of a release; " \
       "release:push is the irreversible half."
  task :build do
    require_relative "release/ordering"
    require "fileutils"

    pkg = File.expand_path("pkg", __dir__)
    FileUtils.rm_rf(pkg)
    FileUtils.mkdir_p(pkg)

    built = Release::Ordering.ordered_specs.map do |spec|
      output = File.join(pkg, "#{spec.name}-#{spec.version}.gem")
      # gem build validates the files list relative to the working directory, so
      # each build runs from its own gem dir; --output writes back into pkg/.
      # --strict escalates any spec warning to a build failure.
      Dir.chdir(File.dirname(spec.loaded_from)) do
        sh "gem build #{File.basename(spec.loaded_from)} --strict --output #{output}"
      end
      File.basename(output)
    end

    puts "\nBuilt #{built.length} gems into pkg/ (build/push order):"
    built.each { |f| puts "  #{f}" }
  end

  desc "Push pkg/*.gem to RubyGems in dependency order (hames first, terret last). " \
       "Run by a human: gem push needs RubyGems MFA. A version already published " \
       "is skipped, so a half-finished release is safe to re-run."
  task :push do
    require_relative "release/ordering"

    published = lambda do |name, version|
      require "open-uri"
      require "json"
      body = URI.open("https://rubygems.org/api/v1/versions/#{name}.json", &:read)
      JSON.parse(body).any? { |v| v["number"] == version.to_s }
    rescue OpenURI::HTTPError
      false # 404 => the gem has never been published, so there is nothing to skip
    end

    Release::Ordering.ordered_specs.each do |spec|
      gem_file = File.expand_path("pkg/#{spec.name}-#{spec.version}.gem", __dir__)
      abort "release:push: #{gem_file} is missing — run `rake release:build` first" unless File.exist?(gem_file)

      if published.call(spec.name, spec.version)
        puts "skip  #{spec.name} #{spec.version} (already on RubyGems)"
        next
      end

      puts "push  #{File.basename(gem_file)}"
      sh "gem push #{gem_file}"
    end
  end
end
