task default: :test

desc "Run all test suites"
task :test do
  Dir["gems/*/test/*_test.rb"].each do |f|
    sh "ruby #{f}"
  end
end

desc "Generate docs/events.md from declared event contracts (CI diffs this)"
task :"events:catalog" do
  require_relative "gems/terret-core/lib/terret"
  rows = Hames.catalog.map { |n, m, d, doc| "| `#{n}` | #{m} | #{d ? 'yes' : ''} | #{doc} |" }
  File.write("docs/events.md", <<~MD)
    # Event Catalog

    Generated by `rake events:catalog`. The dispatch mode is part of each
    event's public contract; the bus enforces it at runtime.

    | Event | Mode | Durable | Description |
    |---|---|---|---|
    #{rows.join("\n")}
  MD
  puts "wrote docs/events.md (#{rows.length} events)"
end

# Rendering for config:catalog, kept off Object so the Rakefile does not grow
# global helpers. Mirrors the events:catalog shape: walk the declarations the
# code registered, sort deterministically, render markdown, and let CI diff it.
module ConfigCatalog
  module_function

  def sections
    entries.map { |gem, klass, schema| section(gem, klass, schema) }
  end

  def entries
    Hames::Schema.declared.map do |klass, schema|
      source = Object.const_source_location(klass.name)&.first.to_s
      gem = source[%r{/gems/([^/]+)/}, 1] || "?"
      [gem, klass, schema]
    end.sort_by { |gem, klass, _| [gem, klass.name] }
  end

  def section(gem, klass, schema)
    key = (klass.respond_to?(:service_key) && klass.service_key) ? " (`#{klass.service_key}`)" : ""
    header = "## #{gem} — `#{klass.name}`#{key}"
    return "#{header}\n\nNo configurable keys.\n" if schema.keys.empty?

    rows = schema.keys.each_value.map do |spec|
      "| `#{spec.name}` | #{type(spec.type)} | #{spec.required ? 'yes' : ''} | " \
        "#{default(spec.default)} | #{doc(spec.doc)} |"
    end
    "#{header}\n\n| Key | Type | Required | Default | Description |\n|---|---|---|---|---|\n#{rows.join("\n")}\n"
  end

  def type(type)
    return "—" if type.nil?

    types = Array(type)
    return "boolean" if types.sort_by(&:name) == [FalseClass, TrueClass]

    types.join(" or ")
  end

  def default(value) = value.nil? ? "—" : "`#{value.inspect}`"
  def doc(text) = text.to_s.gsub("|", "\\|")
end

desc "Run the bench lane (plan §11): dispatch overhead + chunk throughput. " \
     "BENCH_FLOORS=1 asserts each metric against bench/floors.yml and exits 1 below floor"
task :bench do
  require "yaml"
  require_relative "bench/dispatch_overhead"
  require_relative "bench/chunk_throughput"

  results = {}
  results.merge!(Bench::DispatchOverhead.run)
  results.merge!(Bench::ChunkThroughput.run)

  floors = YAML.safe_load_file("bench/floors.yml")

  puts "\nBench summary"
  puts format("%-38s %14s %14s", "metric", "this run", "floor")
  results.each do |metric, value|
    puts format("%-38s %14d %14d", metric, value, floors.fetch(metric))
  end

  next unless ENV["BENCH_FLOORS"]

  failing = results.select { |metric, value| value < floors.fetch(metric) }
  if failing.empty?
    puts "\nBENCH_FLOORS: all #{results.length} metrics at or above floor"
  else
    warn "\nBENCH_FLOORS: below floor: " \
         "#{failing.map { |m, v| "#{m}=#{v} < #{floors.fetch(m)}" }.join(', ')}"
    exit 1
  end
end

desc "Generate docs/config-catalog.md from every service's Hames::Schema (CI diffs this)"
task :"config:catalog" do
  require_relative "gems/terret/lib/terret/boot"
  require_relative "gems/terret/lib/terret/schema_gems"
  # One shared list (Terret::SCHEMA_GEMS), so every schema a shipped bundle can
  # mount is registered before the catalog is written — and a new configurable
  # gem is added in one place the schema tests read too.
  Terret::SCHEMA_GEMS.each { |f| require f }

  sections = ConfigCatalog.sections
  File.write("docs/config-catalog.md", <<~MD)
    # Config Catalog

    Generated by `rake config:catalog`. Every service that declares a
    Hames::Schema is listed with the config keys it reads — type, whether it is
    required, its default, and what it does. CI diffs this, so a config key that
    changes shape shows up in review rather than in a support thread.

    Injectable seams (a transport, a resolver, a client factory) are wiring
    passed in code, never YAML, so they are absent here by design. A service
    with no schema is not listed; doctor reports it as `unschema'd`.

    #{sections.join("\n")}
  MD
  puts "wrote docs/config-catalog.md (#{ConfigCatalog.entries.length} services)"
end
